name: Rust
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Rustfmt
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - uses: actions-rs/clippy-check@v1.0.7
    - name: Run clippy check
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
